"use client";

import { Book, Terminal, Github, Network, Code2, ExternalLink, ChevronRight, Cpu, Shield, Zap, GitBranch } from "lucide-react";
import Link from "next/link";

const docSections = [
    {
        icon: Zap,
        title: "Quick Start",
        color: "#F59E0B",
        items: [
            { title: "Install the GitHub App", description: "Grant ArchSight read access to your repositories in one click.", href: "#" },
            { title: "Run Your First Scan", description: "Select a repo from the Repositories page and trigger AST analysis.", href: "/repositories" },
            { title: "Read the Scan Report", description: "Understand CodeScan, ArchMap, and RiskSight tabs.", href: "#" },
        ],
    },
    {
        icon: Cpu,
        title: "Engine Reference",
        color: "#6C63FF",
        items: [
            { title: "AST Parsing Pipeline", description: "How ArchSight clones, detects frameworks, and parses source files.", href: "#" },
            { title: "Semantic Node Types", description: "HTTP endpoints, DB operations, services, queues — and how they're classified.", href: "#" },
            { title: "Architecture Graph (V3)", description: "Nodes, edges, and the deterministic intermediate representation.", href: "#" },
        ],
    },
    {
        icon: Shield,
        title: "RiskSight Intelligence",
        color: "#FF4C6A",
        items: [
            { title: "Risk Scoring", description: "How the 0–100 risk score is computed from coupling, cycles, and centrality.", href: "#" },
            { title: "Detected Patterns", description: "God Services, Circular Deps, Tight Coupling, and more.", href: "#" },
            { title: "Refactor Strategies", description: "Actionable recommendations generated by the Intelligence Engine.", href: "#" },
        ],
    },
    {
        icon: Network,
        title: "ArchMap Dependency Graph",
        color: "#00D4FF",
        items: [
            { title: "Reading the Graph", description: "Nodes, edges, colours, and what the layout means.", href: "#" },
            { title: "Filtering & Zoom", description: "How to focus on specific layers or node types.", href: "#" },
        ],
    },
    {
        icon: Code2,
        title: "API Reference",
        color: "#22C55E",
        items: [
            { title: "POST /api/scan", description: "Trigger an asynchronous scan for a GitHub repository.", href: "#" },
            { title: "GET /api/scan/:id", description: "Fetch a scan's status, progress, and engine result.", href: "#" },
            { title: "GET /api/intelligence/:id", description: "Retrieve the RiskSight intelligence analysis for a completed scan.", href: "#" },
        ],
    },
];

export default function DocsPage() {
    return (
        <div className="max-w-3xl mx-auto space-y-10">
            {/* Header */}
            <div className="pb-6 border-b border-[#1E1E2E]">
                <p className="text-[#5A5A7A] text-xs font-mono uppercase tracking-widest mb-2">Documentation</p>
                <h1 className="text-3xl font-bold text-white tracking-tight mb-1.5 flex items-center gap-3">
                    <Book className="w-8 h-8 text-[#5A5A7A]" />
                    ArchSight Docs
                </h1>
                <p className="text-[#5A5A7A] text-sm">Everything you need to understand, analyze and act on your codebase architecture.</p>
            </div>

            {/* GitHub link */}
            <a
                href="https://github.com/yugalbansal/ArchSight"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-4 bg-[#13131E] border border-[#1E1E2E] hover:border-white/10 rounded-2xl p-5 transition-all group"
            >
                <div className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center">
                    <Github className="w-5 h-5 text-white" />
                </div>
                <div className="flex-1">
                    <p className="text-white font-semibold text-sm">Open Source on GitHub</p>
                    <p className="text-[#5A5A7A] text-xs mt-0.5">View source, open issues, and contribute to ArchSight.</p>
                </div>
                <ExternalLink className="w-4 h-4 text-[#3E3E5E] group-hover:text-white transition-colors" />
            </a>

            {/* Doc Sections */}
            {docSections.map((section) => (
                <div key={section.title}>
                    <div className="flex items-center gap-2.5 mb-4">
                        <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: `${section.color}18`, border: `1px solid ${section.color}40` }}>
                            <section.icon className="w-4 h-4" style={{ color: section.color }} />
                        </div>
                        <h2 className="text-white font-semibold">{section.title}</h2>
                    </div>
                    <div className="bg-[#13131E] border border-[#1E1E2E] rounded-2xl overflow-hidden divide-y divide-[#1E1E2E]">
                        {section.items.map((item) => (
                            <div
                                key={item.title}
                                className="flex items-center gap-4 px-5 py-4 group hover:bg-white/[0.02] cursor-default"
                            >
                                <div className="flex-1 min-w-0">
                                    <p className="text-white text-sm font-medium flex items-center gap-2">
                                        {item.title}
                                        <span className="text-[10px] font-mono text-[#3E3E5E] bg-[#1E1E2E] px-2 py-0.5 rounded-full border border-[#2E2E3E]">Coming Soon</span>
                                    </p>
                                    <p className="text-[#5A5A7A] text-xs mt-0.5">{item.description}</p>
                                </div>
                                <ChevronRight className="w-4 h-4 text-[#2E2E3E] shrink-0" />
                            </div>
                        ))}
                    </div>
                </div>
            ))}

            {/* Terminal hint */}
            <div className="bg-[#13131E] border border-[#1E1E2E] rounded-2xl p-6">
                <div className="flex items-center gap-2 mb-4">
                    <Terminal className="w-4 h-4 text-[#5A5A7A]" />
                    <h3 className="text-white text-sm font-semibold">Run Your First Scan</h3>
                </div>
                <div className="bg-[#0A0A0F] rounded-xl p-4 font-mono text-xs space-y-2">
                    <p className="text-[#5A5A7A]"># 1. Install the GitHub App and connect your account</p>
                    <p className="text-[#22C55E]">→ <Link href="/repositories" className="underline underline-offset-2">app.archsight.dev/repositories</Link></p>
                    <p className="text-[#5A5A7A] mt-3"># 2. Select a repo and click &quot;Scan Target&quot;</p>
                    <p className="text-[#00D4FF]">→ ArchSight clones, parses, and builds the architecture graph</p>
                    <p className="text-[#5A5A7A] mt-3"># 3. View CodeScan / ArchMap / RiskSight tabs</p>
                    <div className="flex items-center gap-2 text-[#A855F7]">
                        <GitBranch className="w-3 h-3" />
                        <span>Fully deterministic. No AI hallucinations. Static analysis only.</span>
                    </div>
                </div>
            </div>
        </div>
    );
}
